// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<bool> doPair(
        {required String port,
        required String code,
        required String dataFolder}) =>
    RustLib.instance.api
        .crateApiApiDoPair(port: port, code: code, dataFolder: dataFolder);

Future<String> doConnect({required String port, required String dataFolder}) =>
    RustLib.instance.api
        .crateApiApiDoConnect(port: port, dataFolder: dataFolder);

Future<String> doFilter({required String filePath}) =>
    RustLib.instance.api.crateApiApiDoFilter(filePath: filePath);

Future<void> initLogger() => RustLib.instance.api.crateApiApiInitLogger();
