// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.24.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<bool> doPair(
        {required String port,
        required String code,
        required String dataFolder,
        dynamic hint}) =>
    RustLib.instance.api
        .doPair(port: port, code: code, dataFolder: dataFolder, hint: hint);

Future<String> doConnect(
        {required String port, required String dataFolder, dynamic hint}) =>
    RustLib.instance.api
        .doConnect(port: port, dataFolder: dataFolder, hint: hint);

Future<String> doFilter({required String filePath, dynamic hint}) =>
    RustLib.instance.api.doFilter(filePath: filePath, hint: hint);

Future<void> initLogger({dynamic hint}) =>
    RustLib.instance.api.initLogger(hint: hint);
